image:
  name: hashicorp/terraform:light
  entrypoint:
    - "/usr/bin/env"
    - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

variables:
  TFLINT_VERSION: v0.7.2

# cache:
#   paths:
#     - .terraform

stages:
  - "Validate"
  - "Analysis"
  - "Test"
  - "Package"
  - "Deploy"

validate:
  stage: "Validate"
  script:
    - find . -type f -name "*.tf" -exec dirname {} \;|sort -u | while read m; do (terraform validate -check-variables=false "$m" && echo "√ $m") || exit 1 ; done
    - if [[ -n "$(terraform fmt -write=false)" ]]; then echo "Some terraform files need be formatted, run 'terraform fmt' to fix"; exit 1; fi
    - terraform init -input=false
    - terraform validate -check-variables=false

analysis:
  stage: "Analysis"
  script:
    - curl -L -o /tmp/tflint.zip https://github.com/wata727/tflint/releases/download/${TFLINT_VERSION}/tflint_linux_amd64.zip && unzip /tmp/tflint.zip -d /usr/local/bin
    - tflint